version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tinyurl-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i04jq05sol3h"
s3_prefix = "tinyurl-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
